info:
  contact: {}
paths:
  /index:
    get:
      responses: {}
  /user/get_user_list:
    get:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
swagger: "2.0"
