info:
  contact: {}
paths:
  /index:
    get:
      responses: {}
  /user/createUser:
    post:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
  /user/deleteUser:
    delete:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
    put:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
  /user/getUser.email:
    get:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
  /user/getUser.id:
    get:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
  /user/getUser.name:
    get:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
  /user/getUser.phone:
    get:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
  /user/getUserList:
    get:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
  /user/login:
    post:
      responses:
        "200":
          description: code","message","data"}
          schema:
            type: string
  /ws/sendMsg:
    get:
      responses: {}
swagger: "2.0"
